sudo: required
dist: trusty
language: node_js
node_js:
  - '8.9'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - ng test --single-run
  - ng build --prod --base-href ./ --no-aot


after_success:
  - mkdir tmp
  - cd dist
  - pwd
  - zip -r ../tmp/tradeapp.zip ./
  - echo "zipped and saved to ./tmp/tradeapp.zip"
  - cd ..

# delete everything currently in webhosting module
  - |
    curl -X DELETE \
    --user $CUSTOMER:$PASSWORD \
    http://epdemo.apiomat.enterprises/yambas/rest/web/SalesApp1/LIVE \
    --verbose  

# post new build to webhosting module
  - |
    curl -X POST \
    --user $CUSTOMER:$PASSWORD \
    http://epdemo.apiomat.enterprises/yambas/rest/web/SalesApp1/LIVE/ \
    --header "x-apiomat-system: LIVE" \
    --data-binary "@./tmp/tradeapp.zip" \
    --verbose


